name: 🐛 Bug Report / Отчет об ошибке
description: Use only for reporting bugs / Используйте только для сообщений об ошибках
title: "[BUG]: "
labels: ["bug"]
assignees:
  - alaltitov
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ ATTENTION! / ВНИМАНИЕ!
        **This section is only for bug reports! / Этот раздел только для сообщений об ошибках!**
        
        - 💬 Questions & Discussions [Telegram](https://t.me/esphome_lvgl_chats/5)

        - 💬 Вопросы и Обсуждения [Telegram](https://t.me/esphome_lvgl_chats/10)

        - 💡 Ideas / Идеи [Telegram](https://t.me/esphome_lvgl_chats/74)

        ---

  - type: checkboxes
    id: prerequisites
    attributes:
      label: ✅ Prerequisites / Предварительные требования
      description: Make sure you have completed all items / Убедитесь, что вы выполнили все пункты
      options:
        - label: I have checked that the problem is not related to incorrect entity configuration in Home Assistant / Я проверил, что проблема не связана с неправильной конфигурацией сущностей в Home Assistant
          required: true
        - label: I have checked that the problem is not related to incorrect entity configuration in ESPHome / Я проверил, что проблема не связана с неправильной конфигурацией сущностей в ESPHome
          required: true
        - label: I have confirmed this is actually a bug, not a question (use Discussions for questions) / Я подтверждаю, что это действительно ошибка, а не вопрос (используйте Discussions для вопросов)
          required: true

  - type: input
    id: esphome-version
    attributes:
      label: 🔧 ESPHome Version / Версия ESPHome
      description: Specify your ESPHome version (e.g., 2024.7.3) / Укажите вашу версию ESPHome (например, 2024.7.3)
      placeholder: "2024.7.3"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 Bug Description / Описание ошибки
      description: Clearly describe what happens and what was expected / Четко опишите, что происходит и что ожидалось
      placeholder: |
        What happens / Что происходит:
        
        What was expected / Что ожидалось:
        
        Steps to reproduce / Шаги для воспроизведения:
        1. 
        2. 
        3.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📋 Error Logs / Логи ошибок
      description: Paste logs from ESPHome or Home Assistant / Вставьте логи из ESPHome или Home Assistant
      render: shell
      placeholder: |
        Paste error logs here / Вставьте логи ошибок сюда...
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: 📸 Screenshot (if applicable) / Скриншот (если применимо)
      description: Attach a screenshot of the problem if it's a visual error / Прикрепите скриншот проблемы, если это визуальная ошибка
      placeholder: Drag image here or paste link / Перетащите изображение сюда или вставьте ссылку
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: ⚙️ Configuration / Конфигурация
      description: Attach relevant part of your YAML configuration / Прикрепите соответствующую часть вашей YAML конфигурации
      render: yaml
      placeholder: |
        # Paste relevant configuration here / Вставьте соответствующую конфигурацию сюда
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 📎 Additional Information / Дополнительная информация
      description: Any other information that might help / Любая другая информация, которая может помочь
      placeholder: Additional details / Дополнительные детали...
    validations:
      required: false
